# Generated by Django 3.2 on 2024-09-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('day', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('spaces', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dates', models.DateField(blank=True, verbose_name='Date of Event')),
                ('location', models.CharField(max_length=254)),
                ('locale', models.CharField(max_length=254)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guidetrip.categories')),
            ],
        ),
    ]
