# Generated by Django 3.2 on 2024-09-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidetrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='trips',
            options={'verbose_name_plural': 'Trips'},
        ),
        migrations.AddField(
            model_name='trips',
            name='rec_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
