# Generated by Django 3.2 on 2024-09-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidetrip', '0002_auto_20240907_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='Cost',
            new_name='cost',
        ),
    ]
