# Generated by Django 3.2 on 2024-11-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidetrip', '0003_rename_cost_trips_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='dates',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Event'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='day',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Days duration'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='locale',
            field=models.CharField(max_length=254, verbose_name='County/Region location'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='location',
            field=models.CharField(max_length=254, verbose_name='Country location'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='spaces',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Spaces Avialable'),
        ),
    ]
