# Generated by Django 3.2 on 2024-11-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidetrip', '0004_auto_20241102_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={},
        ),
    ]
